### ISSUE TITLE
private deployment request error

### ISSUE THREAD

**Issue by BrightVan** [tavyandy97/span-tree#69] opened 2021-07-30 03:40 UTC
```
https://server_domain/api/v4/projects/group_name%2Fproject_name/repository/tree?per_page=10000&ref=master
```
this requets url is not work. get status code 404
i found another extenssion `gitlab-code-view`, can work well，and  it's request url like this:
```
https://server_domain/group_name/project_name/files/master?format=json
```

**Comment by tavyandy97** [comment] 2021-07-30 08:38
Hey @BrightVan !

Thank you for reporting the issue, I assume you're using an older version of GitLab (i.e. lesser than v12). Could you please confirm your GitLab version?

The reason the latter API wasn't used to form a tree was for optimization purposes. It returns an array of all the filepaths, and in case of repositories with larger number of files (i.e. greater than 10,000) it would require a lot of parsing. 

Therefore the `v4` API was chosen to lazy load all the contents of the tree, rather than loading them all at once. It avoids the string parsing overhead along with fetching only the content that is required.

**Comment by BrightVan** [comment] 2021-07-30 09:09
Hey @tavyandy97 !
my gitlab version is 12.7.5
![image](https://user-images.githubusercontent.com/9381559/127630274-26f21905-d03c-449d-8ae1-fb0542a2b14f.png)

**Comment by tavyandy97** [comment] 2021-07-30 13:06
After looking at the [documentation of GitLab v12.10](https://docs.gitlab.com/12.10/ee/api/repositories.html), I verified that the route does exist and shouldn't have thrown a 404.

Is there any error message with the 404 error? Also, could you please match the API being called with the one mentioned in the documentation?

**Comment by BrightVan** [comment] 2021-08-04 12:17
@tavyandy97
 So , maybe the reason is my gitlab version is too low? the V12.7.5 does not support that route?

**Comment by tavyandy97** [comment] 2021-08-04 16:04
@BrightVan 
Checked the GitLab Archived documentation for v12.7 and seems like the route does exist. After looking around this seems to be an issue with rails and not with GitLab.

Check the following links out

1. [StackOverflow - throws 404 page not found](https://stackoverflow.com/questions/17081675/gitlabs-api-get-projects-id-repository-tree-throws-404-page-not-found)
2. [404s for no apparent reason](https://gitlab.com/gitlab-org/gitlab/-/issues/224669)

**Comment by BrightVan** [comment] 2021-08-11 08:23
i found the bug:
you should use project `id` number, but not `group_name%2Fproject_name`
the api below is ok, just like the offcial document:
```
https://gitlab.example.com/api/v4/projects/{id}/repository/tree
```
request like below, response 404 error.
```
https://gitlab.example.com/api/v4/projects/group_name%2Fproject_name/repository/tree
```
i do not know why your request url  contact with `projects/group_name%2Fproject_name`  but not `id`

**Comment by tavyandy97** [comment] 2021-08-11 09:47
The `files/master?format=json` API is used for the Searchbar popup which is triggered using `Ctrl`/`command`+`p`. However, the `projects/group_name%2Fproject_name/repository/tree` API is used for displaying the tree in the left-side pane. 

This still seems to be a rails configuration issue on your private deployment. I do agree that instead of `group_name%2Fproject_name`, `project_id` could have been used. 

Could you confirm in your older Gitlab v12.x.x deployment whether a `data-project-id` attribute exists in the body (on a repository's page)? 
Once confirmed we can start using `project_id`  instead of `group_name%2Fproject_name`.

**Comment by tavyandy97** [comment] 2021-08-11 09:50
To answer your question, `group_name%2Fproject_name` was used as per the [GitLab documentation](group_name%2Fproject_name). It states both **ID** or **URL encoded path of the project** can be used.

**Comment by BrightVan** [comment] 2021-08-11 09:58
> The `files/master?format=json` API is used for the Searchbar popup which is triggered using `Ctrl`/`command`+`p`. However, the `projects/group_name%2Fproject_name/repository/tree` API is used for displaying the tree in the left-side pane.
> 
> This still seems to be a rails configuration issue on your private deployment. I do agree that instead of `group_name%2Fproject_name`, `project_id` could have been used.
> 
> Could you confirm in your older Gitlab v12.x.x deployment whether a `data-project-id` attribute exists in the body (on a repository's page)?
> Once confirmed we can start using `project_id` instead of `group_name%2Fproject_name`.

i see a old version(12.7.5) project screenshot, the project_id exist.

**Comment by tavyandy97** [comment] 2021-08-11 10:11
My bad, in the [issue I mentioned earlier](https://gitlab.com/gitlab-org/gitlab/-/issues/224669), one of the cases seems to be the `group_name%2Fproject_name` having a `.` character in it. I assume there'll be other cases as well in which it might return a 404. 

I'll start working on the changes, and let you know when they've been released.

Thanks again for reporting the issue 👍

**Comment by tavyandy97** [comment] 2021-08-12 02:43
Hey @BrightVan !

The issue has been resolved and merged. The version (v0.0.4.3) has been updated to the [Chrome Webstore](https://chrome.google.com/webstore/detail/spantree-gitlab-tree/gcjikeldobhnaglcoaejmdlmbienoocg). Will be updating it on Mozilla Addons soon. Would appreciate it if you could verify the fix on your private deployment, and let me know if it works.

Feel free to provide more feedback! Do spread the word about SpanTree 🌳

**Comment by BrightVan** [comment] 2021-08-12 03:35
> Hey @BrightVan !
> 
> The issue has been resolved and merged. The version (v0.0.4.3) has been updated to the [Chrome Webstore](https://chrome.google.com/webstore/detail/spantree-gitlab-tree/gcjikeldobhnaglcoaejmdlmbienoocg). Will be updating it on Mozilla Addons soon. Would appreciate it if you could verify the fix on your private deployment, and let me know if it works.
> 
> Feel free to provide more feedback! Do spread the word about SpanTree 🌳

He @tavyandy97 

Thank you for your work. 
the`projects/project_id/repository/tree` API works well. 
but the `files/master?format=json` API can not work.

i think it's gitlab's bug, the reason is the page is https, but the redirect url is http, chrome block it `(blocked:mixed-content)`. 

and gitlab's page does not add:
```
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
```

**Comment by tavyandy97** [comment] 2021-08-12 05:51
Could you try switching off _Compatibility Mode_? 

Compatibility Mode uses the API `/files/master?format=json`, which causes a redirection to `/-/files/master?format=json`. With _Compatibility Mode_ turned off, there will be no redirection and the extentsion will use `/-/files/master?format=json`.

![image](https://user-images.githubusercontent.com/22865691/129144411-92b37daa-22cd-447d-851e-9c0cf5437d0a.png)

**Comment by BrightVan** [comment] 2021-08-12 06:15
> Could you try switching off _Compatibility Mode_?
> 
> Compatibility Mode uses the API `/files/master?format=json`, which causes a redirection to `/-/files/master?format=json`. With _Compatibility Mode_ turned off, there will be no redirection and the extentsion will use `/-/files/master?format=json`.
> 
> ![image](https://user-images.githubusercontent.com/22865691/129144411-92b37daa-22cd-447d-851e-9c0cf5437d0a.png)

after swithing off Compat Mode, it work well, thanks

**Comment by tavyandy97** [comment] 2021-08-12 07:02
Closing the issue for now. 

Feel free to open a new issue in case you run into an error or have any other concerns. Do spread the word about SpanTree 🌳

**Closed by tavyandy97** 2021-08-12 07:02 UTC
